name: Daily Auto Commit
on:
  schedule:
    # Runs daily at 10:30 UTC (adjust timezone as needed)
    - cron: '30 10 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository with 24f2004230@ds.study.iitm.ac.in email step
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configure Git with email
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "24f2004230@ds.study.iitm.ac.in"
    
    - name: Make a daily commit
      run: |
        # Create or update a timestamp file
        echo "Last auto-commit: $(date)" > daily-update.txt
        # Add and commit changes
        git add daily-update.txt
        git commit -m "Daily auto-commit: $(date)" || exit 0
        git push
