name: Daily Auto Commit
on:
  schedule:
    - cron: '30 2 * * *'  # 2:30 AM UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Git for 24f2004230@ds.study.iitm.ac.in
      run: |
        git config user.name "GitHub Actions"
        git config user.email "24f2004230@ds.study.iitm.ac.in"
    
    - name: Create commit
      run: |
        echo "$(date)" > timestamp.txt
        git add timestamp.txt
        git commit -m "Daily commit: $(date)" || echo "No changes to commit"
        git push
