name: Daily Auto Commit
on:
  schedule:
    - cron: '0 6 * * *'  # 6:00 AM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Git for 24f2004230@ds.study.iitm.ac.in
      run: |
        git config user.name "GitHub Actions"
        git config user.email "24f2004230@ds.study.iitm.ac.in"
    
    - name: Make automated commit
      run: |
        date > .last-updated
        git add .last-updated
        git commit -m "Automated daily update [24f2004230]" || exit 0
        git push
